// <auto-generated />
namespace ServiceBookingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Business_Description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Business_Description));
        
        string IMigrationMetadata.Id
        {
            get { return "202604111529359_Business_Description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
